#cloud-config

# ===================================================================
# --- Configuration Variables ---
# Define variables here using YAML anchors (&) and reference them
# below using aliases (*). This block is for definitions and is
# ignored by cloud-init during processing.
# ===================================================================
setup_variables:
  username: &username "luneth"
  nvim_url: &nvim_url "https://github.com/neovim/neovim/releases/download/v0.11.3/nvim-linux-x86_64.appimage"
  nvim_config_repo: &nvim_config_repo "https://github.com/luneth90/nvim-config.git"
  vectorcode_repo: &vectorcode_repo "git+https://github.com/Davidyz/VectorCode.git"


hostname: ubuntu-server
timezone: utc

# Create user
users:
  - name: *username
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash

# Update system and install base packages
package_update: true
package_upgrade: true
packages:
  - build-essential
  - wget
  - git
  - curl
  - python3
  - python3-pip
  - lua5.3
  - nodejs
  - npm
  - ripgrep
  - pipx

# Run commands to install user-specific tools
runcmd:

  - [ "pipx", "ensurepath", "--global" ]

  - [ su, -, *username, -c, |
      set -ex

      # --- Install Tools ---

      # Install Rust
      curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      # --- Configure Environment ---
      
      # Update .bashrc with correct environment variables for cargo 
      echo 'export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"' >> ~/.bashrc

       # Install VectorCode from its GitHub repository
      npm install tree-sitter-cli
      pipx install *vectorcode_repo

      # --- Setup Neovim ---

      # Create a bin directory for local executables
      mkdir -p ~/.local/bin

      # Download Neovim AppImage and make it executable
      wget -O ~/.local/bin/nvim *nvim_url
      chmod u+x ~/.local/bin/nvim

      # Clone your Neovim config
      # IMPORTANT: This assumes your config files (init.lua, etc.) are at the ROOT of the git repository.
      git clone *nvim_config_repo ~/.config/nvim

      # Sync Neovim plugins with Lazy.nvim
      ~/.local/bin/nvim --headless "+Lazy! sync" +qall
      
      echo "--- User setup completed successfully ---"
    ]

# Optional: Set APT sources
write_files:
  - path: /etc/apt/sources.list
    content: |
      deb http://archive.ubuntu.com/ubuntu/ noble main restricted universe multiverse
      deb http://archive.ubuntu.com/ubuntu/ noble-updates main restricted universe multiverse
      deb http://archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse
      deb http://security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
    permissions: '0644'

# Final message
final_message: "Ubuntu setup completed after $UPTIME seconds"
