#cloud-config

hostname: ubuntu-server
timezone: utc

# Create user 'luneth'
users:
  - name: luneth
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash

# Update system and install base packages
package_update: true
package_upgrade: true
packages:
  - build-essential
  - wget
  - git
  - curl
  - python3
  - python3-pip
  - lua5.3
  - nodejs
  - npm
  - ripgrep

# Run commands to install user-specific tools
runcmd:
  # Use a literal block '|' for a clean, multi-line script.
  # This script is then piped to 'su' to be executed as the 'luneth' user.
  - |
    #!/bin/bash
    cat <<'EOF' | su - luneth
    set -ex

    # --- Install Tools ---

    # Install Rust
    curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    # Install uv (Python tool)
    curl -LsSf https://astral.sh/uv/install.sh | sh

    # --- Configure Environment ---
    
    # Update .bashrc with correct environment variables for cargo and uv
    echo 'export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"' >> ~/.bashrc

    # --- Setup Neovim ---

    # Create a bin directory for local executables
    mkdir -p ~/.local/bin

    # Download Neovim AppImage and make it executable
    wget -O ~/.local/bin/nvim https://github.com/neovim/neovim/releases/download/v0.11.3/nvim-linux-x86_64.appimage
    chmod u+x ~/.local/bin/nvim

    # Clone your Neovim config
    # IMPORTANT: This assumes your config files (init.lua, etc.) are at the ROOT of the git repository.
    git clone https://github.com/luneth90/nvim-config.git ~/.config/nvim

    # Sync Neovim plugins with Lazy.nvim
    ~/.local/bin/nvim --headless "+Lazy! sync" +qall
    
    echo "--- User setup for luneth completed successfully ---"
    EOF

# Optional: Set APT sources
write_files:
  - path: /etc/apt/sources.list
    content: |
      deb http://archive.ubuntu.com/ubuntu/ noble main restricted universe multiverse
      deb http://archive.ubuntu.com/ubuntu/ noble-updates main restricted universe multiverse
      deb http://archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse
      deb http://security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
    permissions: '0644'

# Final message
final_message: "Ubuntu setup completed after $UPTIME seconds"
