#cloud-config

hostname: ubuntu-server
timezone: utc

# Create user 'luneth'
users:
  - name: luneth
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash

# Update system and install base packages
package_update: true
package_upgrade: true
packages:
  - build-essential
  - wget
  - git
  - curl
  - python3
  - python3-pip
  - lua5.3
  - nodejs
  - npm
  - ripgrep

# Run commands to install user-specific tools
runcmd:
  # Install Rust, uv, Neovim, and setup config all as the 'luneth' user
  # The 'su - luneth' ensures commands run in the correct user environment,
  # setting $HOME correctly and placing files in /home/luneth.
  - su - luneth -c '
    set -ex;
    
    # Install Rust
    curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y;
    
    # Install uv (virtual env tool)
    curl -LsSf https://astral.sh/uv/install.sh | sh;
    
    # Update .bashrc with correct environment variables
    # Use double quotes to allow $HOME expansion.
    echo "export PATH=\"$HOME/.cargo/bin:$HOME/.local/bin:$PATH\"" >> ~/.bashrc;
    
    # Create a bin directory for local executables
    mkdir -p ~/.local/bin;
    
    # Download Neovim AppImage using correct wget flag (-O)
    wget -O ~/.local/bin/nvim https://github.com/neovim/neovim/releases/latest/download/nvim.appimage;
    
    # Make it executable
    chmod u+x ~/.local/bin/nvim;

    # Clone Neovim config to the correct directory (~/.config/nvim)
    git clone https://github.com/luneth90/nvim-config.git ~/.config/nvim;
    
    # Sync Neovim plugins with Lazy.nvim
    ~/.local/bin/nvim --headless "+Lazy! sync" +qall;
    '

# Optional: Set APT sources (no change needed here)
write_files:
  - path: /etc/apt/sources.list
    content: |
      deb http://archive.ubuntu.com/ubuntu/ noble main restricted universe multiverse
      deb http://archive.ubuntu.com/ubuntu/ noble-updates main restricted universe multiverse
      deb http://archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse
      deb http://security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
    permissions: '0644'

# Final message
final_message: "Ubuntu setup completed after $UPTIME seconds"
