#cloud-config

hostname: ubuntu-server
timezone: utc

# Create user
users:
  - name: luneth
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash

# Update system and install base packages
package_update: true
package_upgrade: true
packages:
  - build-essential
  - wget
  - git
  - curl
  - python3
  - python3-pip
  - lua5.3
  - nodejs
  - npm
  - ripgrep
  - unzip

# Run commands to install user-specific tools
runcmd:
  # Use a literal block '|' for a clean, multi-line script.
  # This script is then piped to 'su' to be executed as the '' user.
  - |
    #!/bin/bash
    
    cat <<'EOF' | su - luneth
    set -ex

    # --- Install Tools ---

    # Install Rust
    curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    # Install deno
    curl -sSfL https://deno.land/install.sh | sh -s -- -y

    # Install uv
    curl -LsSf https://astral.sh/uv/install.sh | sh


    # --- Configure Environment ---
    
    # Update .bashrc with correct environment variables for cargo and deno
    echo 'export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"' >> ~/.bashrc
    echo 'export PATH="$HOME/.deno/bin:$HOME/.local/bin:$PATH"' >> ~/.bashrc
    source $HOME/.local/bin/env
    source ~/.bashrc

    # Install tree-sitter-cli from sources
    cargo install --locked tree-sitter-cli

    # Install VectorCode 
    uv venv
    source .venv/bin/activate
    uv pip install vectorcode
    uv pip install google-generativeai
    cp ~/.venv/bin/vectorcode ~/.local/bin/

    # --- Setup Neovim ---


    # Download Neovim AppImage and make it executable
    wget -O ~/.local/bin/nvim https://github.com/neovim/neovim/releases/download/v0.11.3/nvim-linux-x86_64.appimage
    chmod u+x ~/.local/bin/nvim

    # Clone your Neovim config
    # IMPORTANT: This assumes your config files (init.lua, etc.) are at the ROOT of the git repository.
    git clone https://github.com/luneth90/nvim-config.git ~/.config/nvim

    # Sync Neovim plugins with Lazy.nvim
    nvim --headless "+Lazy! sync" +qall

    #vectorcode config
    mkdir -p ~/.config/vectorcode
    cp ~/.config/nvim/config.json5 ~/.config/vectorcode/

    #openrouter config
    cp ~/.config/nvim/openrouter.lua ~/.local/share/nvim/lazy/codecompanion.nvim/lua/codecompanion/utils/
    
    echo "--- User setup completed successfully ---"
    EOF

# Optional: Set APT sources
write_files:
  - path: /etc/apt/sources.list
    content: |
      deb http://archive.ubuntu.com/ubuntu/ noble main restricted universe multiverse
      deb http://archive.ubuntu.com/ubuntu/ noble-updates main restricted universe multiverse
      deb http://archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse
      deb http://security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
    permissions: '0644'

# Final message
final_message: "Ubuntu setup completed after $UPTIME seconds"
